export const ROUTES = {
  LOGIN: "/login",
  DASHBOARD: "/overview",
  CAMPUS_FACULTY: "/admin/faculty",
  CAMPUS_STUDY: "/admin/study",
  CAMPUS_COHORTS: "/admin/cohorts",
  CAMPUS_CLASS: "/admin/class",
  ACADEMIC_STUDENT: "/admin/student",
  ACADEMIC_QUESTION_SRQ: "/admin/question",
  ACADEMIC_QUESTION_TRIAGE: "/admin/question-triage",
  ASSESMENT_CUT_OFF: "/admin/cut-off",
  OPERATIONS_SCHEDULE: "/admin/screening-schedule",
  OPERATIONS_SESSION: "/admin/screening-session",
  SCREENING_RESULT: "/admin/screening-result",
  SCREENING_SRQ_RESPONSE: "/admin/screening-srq-20",
  SCREENING_FOLLOW_UP: "/admin/follow-up",
  USER_MANAGEMENT: "/admin/rbac",
  USER_LOG: "/admin/audit-logs",
} as const;
